exclude: >
  (?x)^(
  docs|
  Makefile
  )

repos:
  - repo: git@github.com/PyCQA/flake8
    rev: "3.7.7"
    hooks:
    - id: flake8
      name: flake8
      language: python
      files: \.py$
      language_version: python3.7
      exclude: tests
      additional_dependencies: ['flake8-builtins']

  - repo: git@github.com/pre-commit/pre-commit-hooks
    sha: "v0.7.1"
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: debug-statements
      language: python
      language_version: python3.7
    - id: requirements-txt-fixer
    - id: name-tests-test
      args: ['--django']

  - repo: git@github.com/pre-commit/mirrors-isort
    sha: "v4.3.18"
    hooks:
    - id: isort
      language: python
      language_version: python3.7

  - repo: git@github.com/pre-commit/mirrors-yapf
    rev: "v0.25.0"
    hooks:
    - id: yapf
      args: [-i, -r]
      language: python
      language_version: python3.7
